CREATE DATABASE IF NOT EXISTS yummy_bite CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE yummy_bite;

CREATE TABLE User (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  password VARCHAR(191) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'STUDENT',
  phone VARCHAR(191) NOT NULL DEFAULT '',
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE Dish (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  name VARCHAR(191) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  price DOUBLE NOT NULL,
  category VARCHAR(191) NOT NULL,
  image LONGTEXT NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE DailyMenu (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  quantity INT NOT NULL,
  isActive BOOLEAN NOT NULL DEFAULT TRUE,
  dishId VARCHAR(191) NOT NULL,
  INDEX DailyMenu_dishId_idx (dishId),
  CONSTRAINT DailyMenu_dishId_fkey FOREIGN KEY (dishId) REFERENCES Dish(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `Order` (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  totalAmount DOUBLE NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'PENDING_PAYMENT',
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  studentId VARCHAR(191) NOT NULL,
  INDEX Order_studentId_idx (studentId),
  CONSTRAINT Order_studentId_fkey FOREIGN KEY (studentId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OrderItem (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  quantity INT NOT NULL,
  price DOUBLE NOT NULL,
  orderId VARCHAR(191) NOT NULL,
  dishId VARCHAR(191) NOT NULL,
  INDEX OrderItem_orderId_idx (orderId),
  INDEX OrderItem_dishId_idx (dishId),
  CONSTRAINT OrderItem_orderId_fkey FOREIGN KEY (orderId) REFERENCES `Order`(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT OrderItem_dishId_fkey FOREIGN KEY (dishId) REFERENCES Dish(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Payment (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  screenshot VARCHAR(500) NOT NULL,
  transactionId VARCHAR(191) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  rejectedReason TEXT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  orderId VARCHAR(191) NOT NULL UNIQUE,
  CONSTRAINT Payment_orderId_fkey FOREIGN KEY (orderId) REFERENCES `Order`(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Receipt (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  collectedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  orderId VARCHAR(191) NOT NULL UNIQUE,
  CONSTRAINT Receipt_orderId_fkey FOREIGN KEY (orderId) REFERENCES `Order`(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Review (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  rating INT NOT NULL,
  comment TEXT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  studentId VARCHAR(191) NOT NULL,
  orderId VARCHAR(191) NOT NULL,
  dishId VARCHAR(191) NOT NULL,
  INDEX Review_studentId_idx (studentId),
  INDEX Review_orderId_idx (orderId),
  INDEX Review_dishId_idx (dishId),
  CONSTRAINT Review_studentId_fkey FOREIGN KEY (studentId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT Review_orderId_fkey FOREIGN KEY (orderId) REFERENCES `Order`(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT Review_dishId_fkey FOREIGN KEY (dishId) REFERENCES Dish(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Vote (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  count INT NOT NULL DEFAULT 1,
  week VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  studentId VARCHAR(191) NOT NULL,
  dishId VARCHAR(191) NOT NULL,
  INDEX Vote_studentId_idx (studentId),
  INDEX Vote_dishId_idx (dishId),
  CONSTRAINT Vote_studentId_fkey FOREIGN KEY (studentId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT Vote_dishId_fkey FOREIGN KEY (dishId) REFERENCES Dish(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Ballot (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  week VARCHAR(191) NOT NULL UNIQUE,
  isOpen BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE MealSuggestion (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  description TEXT NOT NULL,
  week VARCHAR(191) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  staffNote TEXT NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  reviewedAt DATETIME(3) NULL,
  suggestedById VARCHAR(191) NOT NULL,
  approvedById VARCHAR(191) NULL,
  INDEX MealSuggestion_suggestedById_idx (suggestedById),
  INDEX MealSuggestion_approvedById_idx (approvedById),
  CONSTRAINT MealSuggestion_suggestedById_fkey FOREIGN KEY (suggestedById) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT MealSuggestion_approvedById_fkey FOREIGN KEY (approvedById) REFERENCES User(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE TransactionLog (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  orderId VARCHAR(191) NOT NULL,
  userId VARCHAR(191) NULL,
  action VARCHAR(191) NOT NULL,
  note TEXT NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX TransactionLog_orderId_idx (orderId),
  INDEX TransactionLog_userId_idx (userId),
  CONSTRAINT TransactionLog_orderId_fkey FOREIGN KEY (orderId) REFERENCES `Order`(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT TransactionLog_userId_fkey FOREIGN KEY (userId) REFERENCES User(id) ON DELETE SET NULL ON UPDATE CASCADE
);
